# SysScope Configuration File

# System monitoring thresholds
thresholds:
  cpu: 90  # CPU usage threshold (percentage)
  memory: 90  # Memory usage threshold (percentage)
  disk: 90  # Disk usage threshold (percentage)

# Network monitoring settings
network:
  ping_target: "8.8.8.8"  # Default ping target for connectivity tests
  ping_count: 3  # Number of pings to perform
  dns_test_domain: "google.com"  # Domain to test DNS resolution

# Logging settings
logging:
  system_log_lines: 10  # Number of system log lines to show
  enable_debug: false  # Enable debug logging

# Report settings
report:
  formats:
    - text  # Generate text report
    - html  # Generate HTML report
  output_dir: "reports"  # Directory to store reports
  include_sections:
    system: true
    resources: true
    processes: true
    network: true
